// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvgjxozohvrdgdrgdgkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2Z2p4b3pvaHZyZGdkcmdkZ2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODk2NjAsImV4cCI6MjA2NDc2NTY2MH0.eoeGEgPdPNSt-YEXdxZTf6cGJzMVXFcpnbWIs8AlnJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);